name: build
on:
   push:
      branches: [ "main" ]
   pull_request:
      branches: [ "main" ]
      
jobs:
   build_job:
      runs-on: ubuntu-latest
      
      steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: opencv
          uses: Dovyski/setup-opencv-action@v1.1
          with: 
            opencv-version: '4.0.0'

        - name: prepare
          run: sudo apt install cmake make g++

        - name: build
          run: |
            cmake -S . -B build
            sudo cmake --install build
            img2ascii --help
