name: build
on:
   push:
      branches: [ "main" ]
   pull_request:
      branches: [ "main" ]
      
jobs:
   build_job:
      runs-on: ubuntu-latest
      
      steps:
        - name: checkout
          uses: actions/checkout@v4
          with:
            submodules: true

        - name: prepare
          run: sudo apt install cmake make g++ opencv

        - name: build
          run: |
            cmake -S . -B build
            sudo cmake --install build
            img2ascii --help
